name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
permissions:
  contents: write

jobs:
  create-release:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-git-cliff
          restore-keys: |
            ${{ runner.os }}-cargo-git-cliff
      - name: Install git-cliff
        run: |
          if ! command -v git-cliff &> /dev/null; then
            cargo install git-cliff
          fi
      - name: Generate Changelog
        run: git cliff --latest -o ${{ github.workspace }}-CHANGELOG.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build ${{ matrix.os }}
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            artifact-name: RestWave-windows-x64
          - os: ubuntu-latest
            runtime: linux-x64
            artifact-name: RestWave-linux-x64
          - os: macos-latest
            runtime: osx-x64
            artifact-name: RestWave-macos-x64
          - os: macos-latest
            runtime: osx-arm64
            artifact-name: RestWave-macos-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true
        cache-dependency-path: RestWave/RestWave.csproj

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/RestWave.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore RestWave/RestWave.csproj

    - name: Build and publish (Self Contained)
      if: matrix.os == 'macos-latest'
      run: dotnet publish RestWave/RestWave.csproj -c Release -r ${{ matrix.runtime }} --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishReadyToRun=true /p:Version=${{ github.ref_name }} /p:AssemblyVersion=${{ github.ref_name }} /p:FileVersion=${{ github.ref_name }} /p:TreatWarningsAsErrors=true -o ./publish/${{ matrix.artifact-name }}

    - name: Build and publish
      if: matrix.os != 'macos-latest'
      run: dotnet publish RestWave/RestWave.csproj -c Release -r ${{ matrix.runtime }} --self-contained false /p:PublishReadyToRun=true /p:Version=${{ github.ref_name }} /p:AssemblyVersion=${{ github.ref_name }}.0 /p:FileVersion=${{ github.ref_name }}.0 /p:TreatWarningsAsErrors=true -o ./publish/${{ matrix.artifact-name }}
    
    - name: Zip published files (Windows)
      if: runner.os == 'Windows'
      run: |
        $source = "./publish/${{ matrix.artifact-name }}/*"
        $destination = "./publish/${{ matrix.artifact-name }}.zip"
        $exclude = Get-ChildItem -Path "./publish/${{ matrix.artifact-name }}" -Recurse -Include *.pdb | ForEach-Object { $_.FullName }
        if ($exclude) {
          Compress-Archive -Path (Get-ChildItem -Path "./publish/${{ matrix.artifact-name }}" -Recurse | Where-Object { $_.Extension -ne ".pdb" } | Select-Object -ExpandProperty FullName) -DestinationPath $destination
        } else {
          Compress-Archive -Path $source -DestinationPath $destination
        }

    - name: Zip published files (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        cd ./publish/${{ matrix.artifact-name }}
        zip -r ../${{ matrix.artifact-name }}.zip . -x '*.pdb'
        cd -
    
    - name: Build Windows Installer
      if: matrix.os == 'windows-latest'
      run: |
        # Download and install Inno Setup
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "inno-setup-installer.exe"
        Start-Process -FilePath "inno-setup-installer.exe" -ArgumentList "/VERYSILENT", "/NORESTART", "/DIR=C:\InnoSetup" -Wait

        # Set version environment variable
        $env:APP_VERSION = "${{ github.ref_name }}"

        # Build installer
        & "C:\InnoSetup\ISCC.exe" setup.iss

        # Move installer to publish folder
        Move-Item "installer\RestWave-Setup-${{ github.ref_name }}.exe" "./publish/"

    - name: Create Artifact
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ runner.os == 'Windows' && './publish/RestWave-Setup-' || './publish/' }}${{ runner.os == 'Windows' && github.ref_name || matrix.artifact-name }}${{ runner.os == 'Windows' && '.exe' || '.zip' }}
